system:
    default:
        fielddefinition_edit_templates:
            - { template: '@EzSystemsRepositoryForms/ContentType/field_types.html.twig', priority: 0 }
        location_view:
            _platformui_content_name:
                content_name:
                    template: '@EzSystemsRepositoryForms/content_name/content_name.html.twig'
                    match: {}
